# This workflow performs automated tests on the official code branch.
# Test 1: compiling the source code and building the executable
# Test 2: performing the regression tests.

name: Python application test

on:
  push:
    branches: [ "patch-3" ]
  pull_request:
    branches: [ "patch-3" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          # source venv/bin/activate
          echo "Compiling SCIANTIX"
          mkdir build
          cd build
          cmake ..
          make
          echo "in build"

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-build
          path: ./build

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: compiled-build
          path: ./build

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install numpy matplotlib scipy scikit-learn

      - name: Run tests
        run: |
          source venv/bin/activate
          echo "In Regression"
          cd regression
          chmod +x ./../build/sciantix.x  # add the execute permission
          python3 ./regression.py
